# Load Test dataset AgNews

In [57]:
import pandas as pd


Ag_news_test = pd.read_csv("Data_Raw_File/raw/ag_news/ag_news_csv/test.csv",sep = ",")
Ag_news_test.columns = ["Article Class", "Title", "Description"]
Ag_news_test 

# https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.map.html

# If labels are already numeric (0,1,2,3), mapping is not required for training, but label2id/id2label is useful for human-readable outputs.
# I originally used maping changes but it gives  error for
#  labels.append(self.Model.label2id[label])
# KeyError: 'Sci/Tech'


mapping_mask = {1:"World" ,2:"Sports",3:"Business",4:"Sci/Tech"}
Ag_news_test["Article Class"] =  Ag_news_test["Article Class"].map(mapping_mask)
Ag_news_test

,Article Class,Title,Description
0,Sci/Tech,The Race is On: Second Private Team Sets Launc...,"SPACE.com - TORONTO, Canada -- A second\team o..."
1,Sci/Tech,Ky. Company Wins Grant to Study Peptides (AP),AP - A company founded by a chemistry research...
2,Sci/Tech,Prediction Unit Helps Forecast Wildfires (AP),AP - It's barely dawn when Mike Fitzpatrick st...
3,Sci/Tech,Calif. Aims to Limit Farm-Related Smog (AP),AP - Southern California's smog-fighting agenc...
4,Sci/Tech,Open Letter Against British Copyright Indoctri...,The British Department for Education and Skill...
...,...,...,...
7594,World,Around the world,Ukrainian presidential candidate Viktor Yushch...
7595,Sports,Void is filled with Clement,With the supply of attractive pitching options...
7596,Sports,Martinez leaves bitter,Like Roger Clemens did almost exactly eight ye...
7597,Business,5 of arthritis patients in Singapore take Bext...,SINGAPORE : Doctors in the United States have ...
7598,Business,EBay gets into rentals,EBay plans to buy the apartment and home renta...

#Basic Test dataset AgNews with all all labels((This is for training and testing how text classfication work))

In [58]:
NLP_base_test = pd.DataFrame({
    "text" : Ag_news_test["Description"],
    "label":  Ag_news_test["Article Class"]
})

NLP_base_test.to_csv("NLP_dataset/Base_test_AgNews.tsv", sep= "\t", index=False,encoding="utf-8")

# Train dataset AgNews

In [59]:
import pandas as pd


Ag_news_train = pd.read_csv("Data_Raw_File/raw/ag_news/ag_news_csv/train.csv",sep = ",")
Ag_news_train.columns = ["Article Class", "Title", "Description"]
Ag_news_train 
mapping_mask = {1:"World" ,2:"Sports",3:"Business",4:"Sci/Tech"}
Ag_news_train ["Article Class"] =  Ag_news_train ["Article Class"].map(mapping_mask)
# https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.map.html
Ag_news_train

,Article Class,Title,Description
0,Business,Carlyle Looks Toward Commercial Aerospace (Reu...,Reuters - Private investment firm Carlyle Grou...
1,Business,Oil and Economy Cloud Stocks' Outlook (Reuters),Reuters - Soaring crude prices plus worries\ab...
2,Business,Iraq Halts Oil Exports from Main Southern Pipe...,Reuters - Authorities have halted oil export\f...
3,Business,"Oil prices soar to all-time record, posing new...","AFP - Tearaway world oil prices, toppling reco..."
4,Business,"Stocks End Up, But Near Year Lows (Reuters)",Reuters - Stocks ended slightly higher on Frid...
...,...,...,...
119994,World,Pakistan's Musharraf Says Won't Quit as Army C...,KARACHI (Reuters) - Pakistani President Perve...
119995,Sports,Renteria signing a top-shelf deal,Red Sox general manager Theo Epstein acknowled...
119996,Sports,Saban not going to Dolphins yet,The Miami Dolphins will put their courtship of...
119997,Sports,Today's NFL games,PITTSBURGH at NY GIANTS Time: 1:30 p.m. Line: ...
119998,Sports,Nets get Carter from Raptors,INDIANAPOLIS -- All-Star Vince Carter was trad...

# Train NLP Train test with all labels(This is for training and testing how text classfication work)

In [60]:
NLP_base_train = pd.DataFrame({  
    "text" : Ag_news_train["Description"],
    "label":  Ag_news_train["Article Class"]
})

# NLP_base_evaluate = pd.DataFrame({
#     "text" : Ag_news_test["Description"]
#     "target" 
# })


NLP_base_train.to_csv("NLP_dataset/Base_train_AgNews.tsv",sep="\t", index=False,encoding="utf-8")